# AT Protocol PubSub Server Configuration

# Server configuration
server:
  # Port to listen on (default: 8080)
  port: "8080"
  # Host to bind to (use "0.0.0.0" for all interfaces, "localhost" for local only)
  host: "localhost"
  # Metrics Port
  metrics_port: "9090"
  # Metrics Host
  metrics_host: "localhost"
  # Maximum number of concurrent WebSocket connections (default: 1000)
  max_connections: 1000
  # Graceful shutdown timeout
  shutdown_timeout: "10s"
  
  # CORS configuration
  cors:
    # Allow all origins (useful for development)
    allow_all_origins: true
    # Specific allowed origins (used when allow_all_origins is false)
    allowed_origins: []
    # Allowed HTTP methods
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    # Allowed headers
    allowed_headers: ["*"]

# AT Protocol firehose configuration
firehose:
  # Firehose WebSocket URL
  url: "wss://bsky.network/xrpc/com.atproto.sync.subscribeRepos"
  # Delay between reconnection attempts
  reconnect_delay: "5s"
  # Maximum number of reconnection attempts (-1 for unlimited)
  max_reconnects: 10
  # WebSocket read timeout
  read_timeout: "60s"
  # WebSocket write timeout
  write_timeout: "10s"
  # Ping interval for keep-alive
  ping_interval: "30s"

# Logging configuration
logging:
  # Log level: debug, info, warn, error
  level: "info"
  # Log format: text, json
  format: "text"
  # Log output: stdout, stderr, or file path
  output: "stdout"
  # Use structured logging
  structured: false