version: '3.8'

services:
  # Default configuration - development
  at-proto-pubsub-dev:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/app/config-docker.yaml
    volumes:
      # Optional: mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production configuration with custom config
  at-proto-pubsub-prod:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/app/config/production.yaml
    volumes:
      # Mount custom production configuration
      - ./config/production.yaml:/app/config/production.yaml:ro
      # Mount logs directory
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # High-capacity configuration
  at-proto-pubsub-scale:
    build: .
    ports:
      - "8080:8080"
    environment:
      - CONFIG_FILE=/app/config/high-capacity.yaml
    volumes:
      # Mount high-capacity configuration
      - ./config/high-capacity.yaml:/app/config/high-capacity.yaml:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Load balancer setup with multiple instances
  at-proto-pubsub-lb1:
    build: .
    ports:
      - "8081:8080"
    environment:
      - CONFIG_FILE=/app/config/load-balanced.yaml
    volumes:
      - ./config/load-balanced.yaml:/app/config/load-balanced.yaml:ro

  at-proto-pubsub-lb2:
    build: .
    ports:
      - "8082:8080"
    environment:
      - CONFIG_FILE=/app/config/load-balanced.yaml
    volumes:
      - ./config/load-balanced.yaml:/app/config/load-balanced.yaml:ro

  # Nginx load balancer (optional)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - at-proto-pubsub-lb1
      - at-proto-pubsub-lb2
    restart: unless-stopped

# Optional: shared volume for configurations
volumes:
  config:
    driver: local